stages:
  - test

.test_job: &test_job
  stage: test
  
  script:
    - /usr/share/games/wesnoth/1.16/data/tools/wmllint --dryrun /usr/share/games/wesnoth/1.16/data/core .

test:default:           
  <<: *test_job                        
  image: konecnyjakub/wesnoth:1.16 
